### ISSUE TITLE
I can connect to the server but Cant get data

### ISSUE THREAD

**Issue by dk-gitiot** [tq-bit/node-red-contrib-server-sent-events#1]
Hi, I have used this node to connect t
![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/113344313/0b733b66-ac87-4634-9460-a6acedee7bba)
o a client. The connection seems fine but I cant get the data back using the node.

**Comment by tq-bit** [comment]
Hello there. Thank you for your report :) 

Please provide a bit more context for me to look into it.

- Did you use the [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) API?
- What does your client look like? 

Please try the following Javascript client example and tell me whether it works for you or not (assuming your node-red server runs on localhost:1880): 

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <script>
    const source = new EventSource('http://localhost:1880/api/sse');

    source.onopen = () => console.log("Open Connection")
    source.onmessage = (ev) => console.log(ev)
  </script>
</body>
</html>
```

**Comment by dk-gitiot** [comment]
Hi Thanks for the prompt reply !

I have used the below for the client. 
`const events = new EventSource('[http://localhost:1880/events'](http://localhost:1880/events%27));
 events.onmessage = (event) => {
       const parsedData = JSON.parse(event.data);
       console.log("Event Data", parsedData);
   };`

I tried your code but When I trigger  using the inject node but when Im getting the sent message only when I deploy the code and no onMesssage.

**Comment by tq-bit** [comment]
Hello again. 

Can you please check in the sse-server node if you have filled the field for "Event"? Or did you set your `msg.topic` property to anything specific?

If you filled either with anything, please try out the following code:

```js
 const events = new EventSource('http://localhost:1880/events');
 events.addEventListener('myMessage', (event) => {
   console.log(event);
 })
```

It assumes that your node's "Event" is filled like so: 

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/69204418/07e1cc44-c2f7-43d8-a014-585368911e9b)

Or your `msg.topic` is equal to "myMessage".

If this doesn't work, please do let me know the browser you're working with and I'll investigate further

**Comment by dk-gitiot** [comment]
Thanks for the reply. I tried it and its working fine now. 

Question: How can I send the message from server to a specific client instead of sending it to many clients? Is there any way to do that or any tweaks that we ought to do?

**Comment by tq-bit** [comment]
Yes, you can have several endpoints, one per client, and control what's getting sent where with the respective Event - Type. Like this:

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/69204418/ab482bc3-7acb-4dc2-b9b1-f3f93e7df206)

Client Code: 

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    const client_one = new EventSource('http://localhost:1880/client_one');
    const client_two = new EventSource('http://localhost:1880/client_two');

    client_one.addEventListener('client_one', (event) => {
      console.log("Client One")
    })

    client_two.addEventListener('client_two', (event) => {
      console.log("Client two")
    })
  </script>
</body>

</html>
```
