### ISSUE TITLE
"Write after end" error

### ISSUE THREAD

**Issue by hemangikhakhi** [tq-bit/node-red-contrib-server-sent-events#3]
As mentioned in https://github.com/tq-bit/node-red-contrib-server-sent-events/issues/2 "Write after end" is still present. When I am deploying the flow after some changes it throws the error and my node-red server automatically stopped and restarted again.
![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/65289141/fcbe2a87-0fdd-4824-9397-c92b353e9c04)

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/65289141/b0e045dd-522a-40b9-bdd8-6592883dae14)

**Comment by hemangikhakhi** [comment]
@tq-bit Is there any updates on this?

**Comment by tq-bit** [comment]
Hello there, 

please send me a few more info about

- Your operating system
- Your deployed Node-red version
