### ISSUE TITLE
Error logs when node is idle for some time

### ISSUE THREAD

**Issue by hemangikhakhi** [tq-bit/node-red-contrib-server-sent-events#4]
When we are not triggering the node and keep it idle for some time i.e. 5 minutes in my case it shows the below error logs.

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/65289141/142ea953-c15f-4962-bfe0-b5ed82b7cde7)

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/65289141/65e7fed0-21c8-480a-b70c-9b64a2e6aeb2)

**Comment by hemangikhakhi** [comment]
@tq-bit Is there any updates on this?

**Comment by tq-bit** [comment]
Hello there,

please send me a few more info about

- Your operating system
- Your deployed Node-red version
- Other nodes you have installed as part of your palette
- Whether or not you're using a reverse proxy
- The value of your `httpRequestTimeout` variable in settings.js
?
