### ISSUE TITLE
double quotes when payload is not an object

### ISSUE THREAD

**Issue by yalinsayi** [tq-bit/node-red-contrib-server-sent-events#6]
Hello, nice work Tobias.

I'm trying to use your node with [HTMX SSE extension](https://htmx.org/extensions/server-sent-events/), it connects and transfers data. My payload is not an object it is just a string, the payload returns "in double quotes" because it tries to serialize it as JSON, so my output has double quotes in it. 

Is it possible to send plain strings with this node?

Thanks.

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/3295118/457bd0f3-9167-4482-9b5d-ac45e958809c)
![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/3295118/dc64dfbe-59df-433f-ad6e-b0c093114348)

**Comment by tq-bit** [comment]
Hello yalin, 

thank you for using my node and for your report :) 
I've patched this behavior out - when the payload is a string, it will not be stringified again.

Please check if this solves your problem.

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/69204418/a75a9bb7-856f-4330-986a-ab0c391d073c)

All the best, 
Tobi

**Comment by yalinsayi** [comment]
Yes it works, 

Thank you Tobias for your attention and quick response, its really appreciated.

Have a nice day :)
