### ISSUE TITLE
Subscriber count does not decrease after client disconnection

### ISSUE THREAD

**Issue by dumdiedum** [tq-bit/node-red-contrib-server-sent-events#7]
Thank you for this great node!

I have one issue: the subscriber count does not decrease after a client disconnects.

I'm using a very similar way to react to the close event, like here:

https://github.com/tq-bit/node-red-contrib-server-sent-events/blob/13bacf2257c13c2fce589bc4ac129d6b6ee4b52a/sse-server/sse-server.js#L49

to tidy up my client states in a function node like this:

`msg.res._res.on('close', function() { ... }`

When I add `req`, I no longer receive close events. Could this be the error?

**Comment by tq-bit** [comment]
Hi dumdiedum, 

thanks for your report :)

The issue with the decreasing subscribers indeed stems from the node update function being called before the subscriber was removed. I've already addressed that and will push a fix now. 

> fix w/ commit #d98c6254141b91fc98af1deab98691f83d1f20da

**Comment by tq-bit** [comment]
New version is available on node red repository. Can you please try and confirm the issue is indeed fixed?

**Comment by dumdiedum** [comment]
I've tried again and now subscriber count is decreasing after disconnect. Nice work and thank you very much! 👋

**Comment by dumdiedum** [comment]
I've tried again and now subscriber count is decreasing after disconnect. Nice work and thank you very much! 👋
